# This file was generated by the docusign_rest:generate_config rake task.
# You can run 'ruby lib/tasks/docusign_task.rb' as many times as you need
# to replace the content of this file with a new config.

require_relative '../lib/docusign_rest'

DocusignRest.configure do |config|
  config.username       = 'jonkinney@gmail.com'
  config.password       = 'MnUWneAH3xqL2G'
  config.integrator_key = 'NAXX-93c39e8c-36c4-4cb5-8099-c4fcedddd7ad'
  config.account_id     = '327367'
  config.endpoint       = 'https://demo.docusign.net/restapi'
  config.api_version    = 'v2'
end
